### ISSUE TITLE
exec /ko-app/cmd: exec format error v0.1.11

### ISSUE THREAD

**Issue by sam-bowman** [BananaOps/homer-k8s#28]
**Describe the bug**
When trying to deploy the operator via the helm chart I am getting the following error on the homer-k8s-controller container in the deployment/pod:
`exec /ko-app/cmd: exec format error`

**Homer-K8s version**
v0.1.11

**To reproduce**
Deploy the app via helm chart into a kubernetes cluster following the instructions in the README.md

**Expected behavior**
Once installed, both the dashboard and controller start up and behave as expected.

**Additional context**
I can add more details if you need, just let me know.

**Comment by jplanckeel** [comment]
Hello, thank you for the issue, i will check this

**Comment by jplanckeel** [comment]
No news, we close. Use latest version please :)
